project:
  type: website
  output-dir: _site
  render:
  - "*.qmd"
  - "!*.md"
execute:
  freeze: auto
author:
  - name: Coltin Colucci
    email: Colucci01@allegheny.edu
website:
  title: "ReadyResearchers Template"
  navbar:
    right:
      - text: "Senior Thesis"
        href: thesis/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: journal
    css: styles.css
